package pe.sumaq.ayllu.caja.sistemacaja.common.exception;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_INVALID_TOKEN,
    AUTH_USER_INACTIVE,
    FORBIDDEN_OPERATION,
    NEGOCIO_EVENTO_FECHAS_INVALIDAS,
    NEGOCIO_EVENTO_TRANSICION_INVALIDA,
    NEGOCIO_EVENTO_NO_ENCONTRADO,
    PRODUCTO_NO_ENCONTRADO,
    PROVEEDOR_NO_ENCONTRADO,
    ROL_NO_ENCONTRADO,
    USUARIO_NO_ENCONTRADO,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
