spring:
  application:
    name: sistema-caja-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  flyway:
    locations: classpath:database/migrations
  jackson:
    default-property-inclusion: non_null

app:
  security:
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET:dev-secret-key-please-change-this-before-production-1234567890}
      expiration: ${APP_SECURITY_JWT_EXPIRATION:PT8H}
